### ISSUE TITLE
v2.1.37 MacOS needs it's execution bit set

### ISSUE THREAD

**Issue by EmbeddedMan** [majenkotech/pic32prog-autotools#1]
Right now, when installing via Arduino IDE, the execute bit is not set on the executable, thus making it not executable enough to execute.

Can the v2.1.37 release be updated with this bit set? Or does a new release need to happen?

**Comment by majenkotech** [comment]
Should be fixed.

**Comment by EmbeddedMan** [comment]
Well, the SHA for the macOS file changed, but when it is downloaded and
unzipped, it sill does not have its execute bit set, and thus still
generates the error when called from the IDE.

*Brian

**Comment by majenkotech** [comment]
Fudgesickles. Right. Try this version.

**Comment by EmbeddedMan** [comment]
Excellent. That one worked. Looks like MacOS is now working just as well as
Windows in chipKIT-core v2.0.0. Thanks!

**Comment by majenkotech** [comment]
I scripted the releasing between last release and this one. I forgot, when copying the binary file, that permissions don't copy along with the file... :blush:
